### PR TITLE
smartfridge you spelt your own name wrong you cretin

### PR DESCRIPTION
**Pull request by skyeredwood**

### CODE REVIEW

**Comment by smartfrigde** [comment]
smartfri**dg**e is taken in npm registry

**Comment by kz-n** [comment]
You cretin you spelt your name wrong

**Comment by skyeredwood** [comment]
yeah but you're not publishing this on NPM

**Comment by skyeredwood** [comment]
it doesnt matter about the username if you dont actually publish it lmao

**Comment by kz-n** [comment]
Draelcord@java

**Comment by kz-n** [comment]
Oh i didn't push the branch :skull:

**Comment by skyeredwood** [comment]
genius

**Comment by smartfrigde** [comment]
> yeah but you're not publishing this on NPM

I DON'T WANNA BE KNOWN AS SMARTFRIDGE BUT SMARTFRIGDE
AAAAAAAAAAAAAAAAAAAAA

**Comment by smartfrigde** [comment]
> Draelcord@java

no

**Comment by kz-n** [comment]
smartfri **gd** e

Confirmed Godot Developer

**Comment by kz-n** [comment]
> > Draelcord@java
> 
> no

Yes

**Comment by smartfrigde** [comment]
if you do that I'll delete your loli hentai stash

**Comment by kz-n** [comment]
Im doing it rn

**Comment by skyeredwood** [comment]
RIP in chat for kz-n's loli hentai stash

**Pull request closed without merging**
